# Generated by Django 5.2.17 on 2026-09-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_default_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelo'),
        ),
    ]
