# Generated by Django 5.2.17 on 2026-09-03 02:02

import django.db.models.functions.text
from django.db import migrations, models


def consolidate_duplicates(apps, schema_editor):
    Categoria = apps.get_model('core', 'Categoria')
    Modelo = apps.get_model('core', 'Modelo')
    Roupa = apps.get_model('core', 'Roupa')

    categories = {}
    for category in Categoria.objects.order_by('id'):
        key = category.categoria.strip().casefold()
        if key in categories:
            keeper = categories[key]
            Modelo.objects.filter(categoria_id=category.id).update(categoria_id=keeper.id)
            category.delete()
        else:
            categories[key] = category

    models_by_category = {}
    for model in Modelo.objects.order_by('id'):
        key = (model.categoria_id, model.modelo.strip().casefold())
        if key in models_by_category:
            keeper = models_by_category[key]
            Roupa.objects.filter(modelo_id=model.id).update(modelo_id=keeper.id)
            model.delete()
        else:
            models_by_category[key] = model


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_roupa_quantidade_estoque_nao_negativa'),
    ]

    operations = [
        migrations.RunPython(consolidate_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('categoria')), name='unique_categoria_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('modelo')), models.F('categoria'), name='unique_modelo_categoria_case_insensitive'),
        ),
    ]
